remote_theme: chrisrhymes/bulma-clean-theme

# Site Settings
lang: es
title: Ingeniería de Características (2022-2)
tagline: MCD-UNISON 
email: julio.waissman@unison.mx
description: Material del curso
baseurl: "/"
url: "https://mcd-unison/ing-caract"
permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: juliowaissman
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
footer_menu: footer

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false

markdown: kramdown
highlighter: rouge

